PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../../

TEST_GROUP := atkins

NED_CFG_test_cmdline_custom = cmdline_custom.cfg

REQUIRES_LIBS := libpthread atkins libloader
DEPENDS_PKGS := libloader

include $(L4DIR)/mk/test.mk
