PKGDIR  ?= ../..
L4DIR   ?= $(PKGDIR)/../..

PKGNAME = atkins

EXTRA_TARGET = debug l4_assert factory ipc_helper app_runner thread_helper \
               format_helper tags \
               kdump introspection_tests \
               fixtures/epiface_provider \
               tap/main tap/tap tap/cmdline tap/main_bundle tap/bundle \
               tap/main_helper tap/cov bare/tap_logger

include $(L4DIR)/mk/include.mk
